$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$sources = @(
  "src/config.js",
  "src/layout.js",
  "src/audio.js",
  "src/game-rules.js",
  "src/render.js",
  "src/overlay-view.js",
  "src/main.js"
)

$bundle = New-Object System.Collections.Generic.List[string]
$bundle.Add("// Generated by scripts/build-standalone.ps1")
$bundle.Add("// Supports direct file:// launches by avoiding ES module loading.")
$bundle.Add("(() => {")
$bundle.Add('  "use strict";')

foreach ($relativePath in $sources) {
  $fullPath = Join-Path $root $relativePath
  $content = [System.IO.File]::ReadAllText($fullPath)
  $content = [regex]::Replace($content, '(?ms)^\s*import[\s\S]*?;\s*', '')
  $content = [regex]::Replace($content, '(?m)^export\s+', '')
  $bundle.Add("")
  $bundle.Add("  // ---- $relativePath ----")
  $bundle.Add($content.Trim())
}

$bundle.Add("})();")

$outputPath = Join-Path $root "src/app-standalone.js"
[System.IO.File]::WriteAllText($outputPath, ($bundle -join [Environment]::NewLine) + [Environment]::NewLine)
